[env]
CARGO_BINS = "cargo-make exa"

[tasks.yay]
command = "yay"
args = ["-Suy"]

[tasks.flatpak]
command = "flatpak"
args = ["update"]

[tasks.rustup]
command = "rustup"
args = ["update"]

[tasks.cargo-bins]
script = [
    """
    CARGO_BINS="${CARGO_BINS}"

    for bin in $CARGO_BINS; do
        cargo install $bin
    done
    """
]

[tasks.default]
alias = "yay"

[tasks.all]
dependencies = ["yay", "flatpak", "rustup", "cargo-bins"]
