[env]
CARGO_BINS = "cargo-make exa"

[tasks.apt_update]
command = "sudo"
args = ["apt", "update"]

[tasks.apt_upgrade]
command = "sudo"
args = ["apt", "upgrade"]

[tasks.apt]
dependencies = ["apt_update", "apt_upgrade"]

[tasks.flatpak]
command = "flatpak"
args = ["update"]

[tasks.rustup]
command = "rustup"
args = ["update"]

[tasks.cargo-bins]
script = [
    """
    CARGO_BINS="${CARGO_BINS}"

    for bin in $CARGO_BINS; do
        cargo install $bin
    done
    """
]

[tasks.default]
alias = "apt"

[tasks.all]
dependencies = ["apt", "flatpak", "rustup", "cargo-bins"]
