[env]
CARGO_BINS = "cargo-make exa"

[tasks.yay]
command = "yay"
args = ["-Suy"]

[tasks.flatpak]
script = "sudo flatpak update"

[tasks.rustup]
command = "rustup"
args = ["update"]

[tasks.cargo-bins]
script = [
    """
    CARGO_BINS="${CARGO_BINS}"

    for bin in $CARGO_BINS; do
        cargo install $bin
    done
    """
]

[tasks.nvim-nightly]
script = [
    """
    wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage -O /tmp/nvim.appimage && \
    mv /tmp/nvim.appimage ~/Downloads/nvim.appimage && \
    chmod +x ~/Downloads/nvim.appimage
    """
]

[tasks.default]
alias = "yay"

[tasks.all]
dependencies = ["yay", "flatpak", "rustup", "cargo-bins"]
