
[Editor]
# Makes the application window frameless.
BorderlessWindow = false


FontFamily = "JetBrainsMono Nerd Font Mono"
FontSize = 12

ExtCmdline   = false
ExtPopupmenu = true
ExtTabline   = false
ExtMessages  = false


# Animates the scrolling behavior of Neovim when the scroll command is entered.
SmoothScroll = false

DisableLigatures = true

# Enable desktop notification settings for nvim messages.
# This option works only if `ExtMessages` is enabled.
DesktopNotifications = true

[SideBar]
# Specifies whether to show the external sidebar or not.
Visible = false

[Palette]
## Specifies the proportion of the command line palette to the height of the entire window.
AreaRatio = 0.5

[Statusline]
## Whether or not to display the external status line
Visible = false

[Cursor]
SmoothMove = false
