format = "$all$kubernetes$line_break$character"

[character]
format = "[>](dimmed white)$symbol"
success_symbol = "[ Î» ](green)"
error_symbol = "[ Î» ](red)"

[hostname]
ssh_only = true
format = "[$hostname ](dimmed white)"

[username]
show_always = false

[directory]
style = "bold white"
format = "> [$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "\\[[$symbol$branch]($style)\\] "

[package]
format = "\\[[$symbol$version]($style)\\] "
disabled = true

[rust]
symbol = "îž¨"
format = "\\[[$symbol $version]($style)\\] "

[golang]
symbol = "îœ¤"
format = "\\[[$symbol $version]($style)\\] "

[lua]
symbol = "î˜ "
format = "\\[[$symbol $version]($style)\\] "
disabled = true

[nodejs]
symbol = "ó°Ž™"
format = "\\[[$symbol $version]($style)\\] "

[python]
symbol = "îˆµ"
format = "\\[[${symbol} ${version}( \\($virtualenv\\))]($style)\\] "

[ruby]
symbol = "îœ¹"
format = "\\[[$symbol $version]($style)\\] "

[cmd_duration]
format = "\\[[ó±«Œ $duration]($style)\\] "

[gcloud]
disabled = true

[java]
disabled = true

[kubernetes]
format = "\\[[$symbol$context]($style)\\] "
disabled = false
detect_folders = []
[kubernetes.context_aliases]
"arn:aws:eks:.*:cluster/\\d+_(?P<name>)_(?P<env>)_.*" = "$name.$env"

[docker_context]
disabled = true

[custom.shell_counter]
command = "source ~/dev/shell_recursive_counter.sh && shell_counter"
format = "\\[[[$symbol](bold grey) $output]($style)\\] "
when = "source ~/dev/shell_recursive_counter.sh && shell_counter"
shell = ["zsh", "-l"]
symbol = "ï’‰"
style = "white"

[custom.pyenv]
command = "source ~/.zshrc && pyenv version 2>/dev/null | cut -c-5"
format = "\\[[[$symbol](bold blue) $output]($style)\\] "
when = "! [ -z $PYENV_ROOT ]"
shell = ["zsh", "-l"]
symbol = "îˆµ"
style = "white"

[custom.rosetta_shell]
command = "echo ðŸŒ¹"
format = "\\[[$output]($style)\\] "
when = "! [ -z $ROSETTA_SHELL ]"
shell = ["zsh", "-l"]
symbol = ""
style = "white"

