[character]
format = "[[>](dimmed white) Î» ](green)"
success_symbol = "green"

[hostname]
ssh_only = false
format = "[$hostname ](dimmed white)"

[username]
show_always = false

[directory]
style = "bold white"

[git_branch]
format = "\\[[$symbol$branch]($style)\\] "

[package]
format = "\\[[$symbol$version]($style)\\] "

[rust]
symbol = "îž¨"
format = "\\[[$symbol $version]($style)\\] "

[golang]
symbol = "îœ¤"
format = "\\[[$symbol $version]($style)\\] "

[lua]
symbol = "î˜ "
format = "\\[[$symbol $version]($style)\\] "
disabled = true

[nodejs]
symbol = "ï¢˜"
format = "\\[[$symbol $version]($style)\\] "

[python]
symbol = "îˆµ"
format = "\\[[${symbol} ${version}( \\($virtualenv\\))]($style)\\] "

[cmd_duration]
format = "\\[[ï¨š$duration]($style)\\] "

[custom.shell_counter]
command = "source ~/dev/shell_recursive_counter.sh && shell_counter"
format = "\\[[[$symbol](bold grey) $output]($style)\\] "
when = "source ~/dev/shell_recursive_counter.sh && shell_counter"
shell = ["zsh", "-l"]
symbol = "ï’‰"
style = "white"

[custom.pyenv]
command = "source ~/.zshrc && pyenv version 2>/dev/null | cut -c-5"
format = "\\[[[$symbol](bold blue) $output]($style)\\] "
when = "! [ -z $PYENV_ROOT ]"
shell = ["zsh", "-l"]
symbol = "îˆµ"
style = "white"

[custom.rosetta_shell]
command = "echo ðŸŒ¹"
format = "\\[[$output]($style)\\] "
when = "! [ -z $ROSETTA_SHELL ]"
shell = ["zsh", "-l"]
symbol = ""
style = "white"

[gcloud]
disabled = true

[java]
disabled = true

