require("plugins")
require("options")
require("keybindings")
require("asynctasks")
require("easymotion")
require("floaterm")
require("vim-test")
require("title")
require("treesitter")
require("workspace")
require("telescope_setup")

--require("lsp")
require("coc")
require("vimspector")

require("statusline")
require("window_picker")

require("misc")
