require("plugins")
require("colorscheme")
require("options")
require("keybindings")
require("asynctasks")
require("easymotion")
require("floaterm")
require("vim-test")
require("title")
require("treesitter")
require("workspace")
require("telescope_setup")

require("lsp")
require("saga")
require("completion")
-- require("coc")
--require("vimspector")
require("dap_setup")

require("statusline")
require("window_picker")

require("sidebar")
require("misc")
require("notes")
require("folding_utils")
